name: Testit
on: workflow_dispatch
permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.63.0-noble
    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - name: Testi 1
        run: npm test -- test1 > test1.txt 2>&1 || true

      - name: Testi 2
        run: npm test -- test2 > testi2.txt 2>&1 || true

      - name: Push
        if: always()
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "github-actions"
          git add test1.txt testi2.txt
          git commit -m "tests" || true
          git push

      - name: Ilmoita virheestä
        if: failure()
        run: echo "Testit epäonnistuivat"
